name = "RecurrenceRelationshipArrays"
uuid = "b889d2dc-af3c-4820-88a8-238fa91d3518"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.1"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecurrenceRelationships = "807425ed-42ea-44d6-a357-6771516d7b2c"

[compat]
ArrayLayouts = "1"
BandedMatrices = "1"
ClassicalOrthogonalPolynomials = "0.13"
FillArrays = "1"
InfiniteArrays = "0.14"
LazyArrays = "2"
SpecialFunctions = "1, 2"
RecurrenceRelationships = "0.0.1, 0.0.2"
julia = "1.10"

[extras]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ClassicalOrthogonalPolynomials", "Test"]
